// SPDX-FileCopyrightText: Copyright Aston89 (Baudelaire)
// SPDX-License-Identifier: GPL-3.0-only

#version 450
#ifndef PSMAA_LUMA_FORMAT
#define PSMAA_LUMA_FORMAT r16f
#endif
#ifndef PSMAA_VECTOR_FORMAT
#define PSMAA_VECTOR_FORMAT rg16f
#endif
#ifndef CMAA_EDGE_FORMAT
#define CMAA_EDGE_FORMAT r8ui
#endif

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(push_constant, std430) uniform type_PushConstant_Constants
{
    vec4 metrics;
    vec4 target;
    uint history_valid;
} params;

layout(set = 0, binding = 0) uniform texture2D tex0;
layout(set = 0, binding = 9) uniform sampler linear_sampler;
layout(set = 0, binding = 10, rgba16f) uniform writeonly image2D output0;

void main()
{
    do
    {
        if (any(greaterThanEqual(gl_GlobalInvocationID.xy, uvec2(params.target.zw))))
        {
            break;
        }
        vec2 _68 = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) * params.metrics.xy;
        vec3 _76 = textureLod(sampler2D(tex0, linear_sampler), _68, 0.0).xyz;
        vec3 _107 = _76 - ((((textureLod(sampler2D(tex0, linear_sampler), _68 + vec2(params.metrics.x, 0.0), 0.0).xyz + textureLod(sampler2D(tex0, linear_sampler), _68 + vec2(-params.metrics.x, 0.0), 0.0).xyz) + textureLod(sampler2D(tex0, linear_sampler), _68 + vec2(0.0, params.metrics.y), 0.0).xyz) + textureLod(sampler2D(tex0, linear_sampler), _68 + vec2(0.0, -params.metrics.y), 0.0).xyz) * 0.25);
        vec3 _114 = _76 + (_107 * (0.20000000298023223876953125 * clamp(abs(dot(_107, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875))) * 48.75670623779296875, 0.0, 1.0)));
        float _115 = abs(0.0);
        imageStore(output0, ivec2(gl_GlobalInvocationID.xy), vec4(clamp(mix(_114, _114, vec3(float(_115 > 0.001000000047497451305389404296875))), vec3(0.0), vec3(1.0)), 1.0));
        break;
    } while(false);
}
