// SPDX-FileCopyrightText: Copyright Aston89 (Baudelaire)
// SPDX-License-Identifier: GPL-3.0-only

#version 450
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_EXT_spirv_intrinsics : require
#ifndef PSMAA_LUMA_FORMAT
#define PSMAA_LUMA_FORMAT r16f
#endif
#ifndef PSMAA_VECTOR_FORMAT
#define PSMAA_VECTOR_FORMAT rg16f
#endif
#ifndef CMAA_EDGE_FORMAT
#define CMAA_EDGE_FORMAT r8ui
#endif

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(push_constant, std430) uniform type_PushConstant_Constants
{
    vec4 metrics;
    vec4 target;
    uint history_valid;
} params;

layout(set = 0, binding = 0) uniform texture2D tex0;
layout(set = 0, binding = 1) uniform texture2D tex1;
layout(set = 0, binding = 2) uniform texture2D tex2;
layout(set = 0, binding = 8) uniform sampler point_sampler;
layout(set = 0, binding = 9) uniform sampler linear_sampler;
layout(set = 0, binding = 10, rgba16f) uniform writeonly image2D output0;
layout(set = 0, binding = 11, rgba16f) uniform writeonly image2D output1;

spirv_instruction(set = "GLSL.std.450", id = 79) float spvNMin(float, float);
spirv_instruction(set = "GLSL.std.450", id = 79) vec2 spvNMin(vec2, vec2);
spirv_instruction(set = "GLSL.std.450", id = 79) vec3 spvNMin(vec3, vec3);
spirv_instruction(set = "GLSL.std.450", id = 79) vec4 spvNMin(vec4, vec4);
spirv_instruction(set = "GLSL.std.450", id = 80) float spvNMax(float, float);
spirv_instruction(set = "GLSL.std.450", id = 80) vec2 spvNMax(vec2, vec2);
spirv_instruction(set = "GLSL.std.450", id = 80) vec3 spvNMax(vec3, vec3);
spirv_instruction(set = "GLSL.std.450", id = 80) vec4 spvNMax(vec4, vec4);

void main()
{
    do
    {
        if (any(greaterThanEqual(gl_GlobalInvocationID.xy, uvec2(params.target.zw))))
        {
            break;
        }
        vec2 _116 = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) * params.metrics.xy;
        vec4 _910;
        vec4 _911;
        if (params.history_valid == 0u)
        {
            vec4 _906 = texelFetch(tex0, ivec3(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y), 0).xy, 0);
            _906.w = dot(_906.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875));
            _910 = _906;
            _911 = vec4(0.0);
        }
        else
        {
            vec2 _127 = vec2(params.metrics.x, params.metrics.y);
            vec3 _131 = textureLod(sampler2D(tex0, linear_sampler), _116, 0.0).xyz;
            vec3 _135 = vec3(dot(_131, vec3(0.25, 0.5, 0.25)), dot(_131, vec3(0.5, 0.0, -0.5)), dot(_131, vec3(-0.25, 0.5, -0.25)));
            vec2 _137 = _116 + (vec2(-1.0) * _127);
            vec3 _141 = textureLod(sampler2D(tex0, linear_sampler), _137, 0.0).xyz;
            vec3 _145 = vec3(dot(_141, vec3(0.25, 0.5, 0.25)), dot(_141, vec3(0.5, 0.0, -0.5)), dot(_141, vec3(-0.25, 0.5, -0.25)));
            vec2 _149 = _116 + (vec2(0.0, -1.0) * _127);
            vec3 _153 = textureLod(sampler2D(tex0, linear_sampler), _149, 0.0).xyz;
            vec3 _157 = vec3(dot(_153, vec3(0.25, 0.5, 0.25)), dot(_153, vec3(0.5, 0.0, -0.5)), dot(_153, vec3(-0.25, 0.5, -0.25)));
            vec2 _162 = _116 + (vec2(1.0, -1.0) * _127);
            vec3 _166 = textureLod(sampler2D(tex0, linear_sampler), _162, 0.0).xyz;
            vec3 _170 = vec3(dot(_166, vec3(0.25, 0.5, 0.25)), dot(_166, vec3(0.5, 0.0, -0.5)), dot(_166, vec3(-0.25, 0.5, -0.25)));
            vec2 _175 = _116 + (vec2(-1.0, 0.0) * _127);
            vec3 _179 = textureLod(sampler2D(tex0, linear_sampler), _175, 0.0).xyz;
            vec3 _183 = vec3(dot(_179, vec3(0.25, 0.5, 0.25)), dot(_179, vec3(0.5, 0.0, -0.5)), dot(_179, vec3(-0.25, 0.5, -0.25)));
            vec2 _188 = _116 + (vec2(1.0, 0.0) * _127);
            vec3 _192 = textureLod(sampler2D(tex0, linear_sampler), _188, 0.0).xyz;
            vec3 _196 = vec3(dot(_192, vec3(0.25, 0.5, 0.25)), dot(_192, vec3(0.5, 0.0, -0.5)), dot(_192, vec3(-0.25, 0.5, -0.25)));
            vec2 _201 = _116 + (vec2(-1.0, 1.0) * _127);
            vec3 _205 = textureLod(sampler2D(tex0, linear_sampler), _201, 0.0).xyz;
            vec3 _209 = vec3(dot(_205, vec3(0.25, 0.5, 0.25)), dot(_205, vec3(0.5, 0.0, -0.5)), dot(_205, vec3(-0.25, 0.5, -0.25)));
            vec2 _214 = _116 + (vec2(0.0, 1.0) * _127);
            vec3 _218 = textureLod(sampler2D(tex0, linear_sampler), _214, 0.0).xyz;
            vec3 _222 = vec3(dot(_218, vec3(0.25, 0.5, 0.25)), dot(_218, vec3(0.5, 0.0, -0.5)), dot(_218, vec3(-0.25, 0.5, -0.25)));
            vec2 _226 = _116 + _127;
            vec3 _230 = textureLod(sampler2D(tex0, linear_sampler), _226, 0.0).xyz;
            vec3 _234 = vec3(dot(_230, vec3(0.25, 0.5, 0.25)), dot(_230, vec3(0.5, 0.0, -0.5)), dot(_230, vec3(-0.25, 0.5, -0.25)));
            vec3 _236 = spvNMin(spvNMin(spvNMin(spvNMin(spvNMin(spvNMin(spvNMin(spvNMin(_135, _145), _157), _170), _183), _196), _209), _222), _234);
            vec3 _237 = spvNMax(spvNMax(spvNMax(spvNMax(spvNMax(spvNMax(spvNMax(spvNMax(_135, _145), _157), _170), _183), _196), _209), _222), _234);
            vec4 _243 = textureLod(sampler2D(tex1, point_sampler), _116, 0.0);
            float _250 = dot(_131, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875));
            float _252 = abs(dot(_243.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
            vec4 _255 = textureLod(sampler2D(tex1, point_sampler), _137, 0.0);
            float _259 = abs(dot(_255.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
            bool _260 = _259 < _252;
            float _261 = _260 ? _259 : _252;
            vec4 _266 = textureLod(sampler2D(tex1, point_sampler), _149, 0.0);
            float _270 = abs(dot(_266.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
            bool _271 = _270 < _261;
            float _272 = _271 ? _270 : _261;
            vec4 _277 = textureLod(sampler2D(tex1, point_sampler), _162, 0.0);
            float _281 = abs(dot(_277.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
            bool _282 = _281 < _272;
            float _283 = _282 ? _281 : _272;
            vec4 _288 = textureLod(sampler2D(tex1, point_sampler), _175, 0.0);
            float _292 = abs(dot(_288.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
            bool _293 = _292 < _283;
            float _294 = _293 ? _292 : _283;
            vec4 _299 = textureLod(sampler2D(tex1, point_sampler), _188, 0.0);
            float _303 = abs(dot(_299.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
            bool _304 = _303 < _294;
            float _305 = _304 ? _303 : _294;
            vec4 _310 = textureLod(sampler2D(tex1, point_sampler), _201, 0.0);
            float _314 = abs(dot(_310.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
            bool _315 = _314 < _305;
            float _316 = _315 ? _314 : _305;
            vec4 _321 = textureLod(sampler2D(tex1, point_sampler), _214, 0.0);
            float _325 = abs(dot(_321.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
            bool _326 = _325 < _316;
            float _327 = _326 ? _325 : _316;
            vec4 _332 = textureLod(sampler2D(tex1, point_sampler), _226, 0.0);
            float _336 = abs(dot(_332.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
            bool _337 = _336 < _327;
            float _338 = _337 ? _336 : _327;
            vec4 _340 = mix(mix(mix(mix(mix(mix(mix(mix(_243, _255, bvec4(_260)), _266, bvec4(_271)), _277, bvec4(_282)), _288, bvec4(_293)), _299, bvec4(_304)), _310, bvec4(_315)), _321, bvec4(_326)), _332, bvec4(_337));
            int _341 = abs(-2);
            bool _342 = _341 != 2;
            bool _346;
            if (_342)
            {
                _346 = _341 == 2;
            }
            else
            {
                _346 = true;
            }
            float _362;
            vec4 _363;
            if (_346)
            {
                vec4 _353 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(-2.0) * _127), 0.0);
                float _357 = abs(dot(_353.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _358 = _357 < _338;
                _362 = _358 ? _357 : _338;
                _363 = mix(_340, _353, bvec4(_358));
            }
            else
            {
                _362 = _338;
                _363 = _340;
            }
            int _364 = abs(-1);
            bool _365 = _364 != 2;
            bool _369;
            if (_365)
            {
                _369 = _341 == 2;
            }
            else
            {
                _369 = true;
            }
            float _385;
            vec4 _386;
            if (_369)
            {
                vec4 _376 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(-1.0, -2.0) * _127), 0.0);
                float _380 = abs(dot(_376.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _381 = _380 < _362;
                _385 = _381 ? _380 : _362;
                _386 = mix(_363, _376, bvec4(_381));
            }
            else
            {
                _385 = _362;
                _386 = _363;
            }
            int _387 = abs(0);
            bool _388 = _387 != 2;
            bool _392;
            if (_388)
            {
                _392 = _341 == 2;
            }
            else
            {
                _392 = true;
            }
            float _408;
            vec4 _409;
            if (_392)
            {
                vec4 _399 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(0.0, -2.0) * _127), 0.0);
                float _403 = abs(dot(_399.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _404 = _403 < _385;
                _408 = _404 ? _403 : _385;
                _409 = mix(_386, _399, bvec4(_404));
            }
            else
            {
                _408 = _385;
                _409 = _386;
            }
            int _410 = abs(1);
            bool _411 = _410 != 2;
            bool _415;
            if (_411)
            {
                _415 = _341 == 2;
            }
            else
            {
                _415 = true;
            }
            float _431;
            vec4 _432;
            if (_415)
            {
                vec4 _422 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(1.0, -2.0) * _127), 0.0);
                float _426 = abs(dot(_422.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _427 = _426 < _408;
                _431 = _427 ? _426 : _408;
                _432 = mix(_409, _422, bvec4(_427));
            }
            else
            {
                _431 = _408;
                _432 = _409;
            }
            int _433 = abs(2);
            bool _434 = _433 != 2;
            bool _438;
            if (_434)
            {
                _438 = _341 == 2;
            }
            else
            {
                _438 = true;
            }
            float _454;
            vec4 _455;
            if (_438)
            {
                vec4 _445 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(2.0, -2.0) * _127), 0.0);
                float _449 = abs(dot(_445.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _450 = _449 < _431;
                _454 = _450 ? _449 : _431;
                _455 = mix(_432, _445, bvec4(_450));
            }
            else
            {
                _454 = _431;
                _455 = _432;
            }
            bool _459;
            if (_342)
            {
                _459 = _364 == 2;
            }
            else
            {
                _459 = true;
            }
            float _475;
            vec4 _476;
            if (_459)
            {
                vec4 _466 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(-2.0, -1.0) * _127), 0.0);
                float _470 = abs(dot(_466.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _471 = _470 < _454;
                _475 = _471 ? _470 : _454;
                _476 = mix(_455, _466, bvec4(_471));
            }
            else
            {
                _475 = _454;
                _476 = _455;
            }
            bool _480;
            if (_365)
            {
                _480 = _364 == 2;
            }
            else
            {
                _480 = true;
            }
            float _494;
            vec4 _495;
            if (_480)
            {
                vec4 _485 = textureLod(sampler2D(tex1, point_sampler), _137, 0.0);
                float _489 = abs(dot(_485.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _490 = _489 < _475;
                _494 = _490 ? _489 : _475;
                _495 = mix(_476, _485, bvec4(_490));
            }
            else
            {
                _494 = _475;
                _495 = _476;
            }
            bool _499;
            if (_388)
            {
                _499 = _364 == 2;
            }
            else
            {
                _499 = true;
            }
            float _513;
            vec4 _514;
            if (_499)
            {
                vec4 _504 = textureLod(sampler2D(tex1, point_sampler), _149, 0.0);
                float _508 = abs(dot(_504.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _509 = _508 < _494;
                _513 = _509 ? _508 : _494;
                _514 = mix(_495, _504, bvec4(_509));
            }
            else
            {
                _513 = _494;
                _514 = _495;
            }
            bool _518;
            if (_411)
            {
                _518 = _364 == 2;
            }
            else
            {
                _518 = true;
            }
            float _532;
            vec4 _533;
            if (_518)
            {
                vec4 _523 = textureLod(sampler2D(tex1, point_sampler), _162, 0.0);
                float _527 = abs(dot(_523.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _528 = _527 < _513;
                _532 = _528 ? _527 : _513;
                _533 = mix(_514, _523, bvec4(_528));
            }
            else
            {
                _532 = _513;
                _533 = _514;
            }
            bool _537;
            if (_434)
            {
                _537 = _364 == 2;
            }
            else
            {
                _537 = true;
            }
            float _553;
            vec4 _554;
            if (_537)
            {
                vec4 _544 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(2.0, -1.0) * _127), 0.0);
                float _548 = abs(dot(_544.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _549 = _548 < _532;
                _553 = _549 ? _548 : _532;
                _554 = mix(_533, _544, bvec4(_549));
            }
            else
            {
                _553 = _532;
                _554 = _533;
            }
            bool _558;
            if (_342)
            {
                _558 = _387 == 2;
            }
            else
            {
                _558 = true;
            }
            float _574;
            vec4 _575;
            if (_558)
            {
                vec4 _565 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(-2.0, 0.0) * _127), 0.0);
                float _569 = abs(dot(_565.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _570 = _569 < _553;
                _574 = _570 ? _569 : _553;
                _575 = mix(_554, _565, bvec4(_570));
            }
            else
            {
                _574 = _553;
                _575 = _554;
            }
            bool _579;
            if (_365)
            {
                _579 = _387 == 2;
            }
            else
            {
                _579 = true;
            }
            float _593;
            vec4 _594;
            if (_579)
            {
                vec4 _584 = textureLod(sampler2D(tex1, point_sampler), _175, 0.0);
                float _588 = abs(dot(_584.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _589 = _588 < _574;
                _593 = _589 ? _588 : _574;
                _594 = mix(_575, _584, bvec4(_589));
            }
            else
            {
                _593 = _574;
                _594 = _575;
            }
            bool _598;
            if (_388)
            {
                _598 = _387 == 2;
            }
            else
            {
                _598 = true;
            }
            float _612;
            vec4 _613;
            if (_598)
            {
                vec4 _603 = textureLod(sampler2D(tex1, point_sampler), _116, 0.0);
                float _607 = abs(dot(_603.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _608 = _607 < _593;
                _612 = _608 ? _607 : _593;
                _613 = mix(_594, _603, bvec4(_608));
            }
            else
            {
                _612 = _593;
                _613 = _594;
            }
            bool _617;
            if (_411)
            {
                _617 = _387 == 2;
            }
            else
            {
                _617 = true;
            }
            float _631;
            vec4 _632;
            if (_617)
            {
                vec4 _622 = textureLod(sampler2D(tex1, point_sampler), _188, 0.0);
                float _626 = abs(dot(_622.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _627 = _626 < _612;
                _631 = _627 ? _626 : _612;
                _632 = mix(_613, _622, bvec4(_627));
            }
            else
            {
                _631 = _612;
                _632 = _613;
            }
            bool _636;
            if (_434)
            {
                _636 = _387 == 2;
            }
            else
            {
                _636 = true;
            }
            float _652;
            vec4 _653;
            if (_636)
            {
                vec4 _643 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(2.0, 0.0) * _127), 0.0);
                float _647 = abs(dot(_643.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _648 = _647 < _631;
                _652 = _648 ? _647 : _631;
                _653 = mix(_632, _643, bvec4(_648));
            }
            else
            {
                _652 = _631;
                _653 = _632;
            }
            bool _657;
            if (_342)
            {
                _657 = _410 == 2;
            }
            else
            {
                _657 = true;
            }
            float _673;
            vec4 _674;
            if (_657)
            {
                vec4 _664 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(-2.0, 1.0) * _127), 0.0);
                float _668 = abs(dot(_664.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _669 = _668 < _652;
                _673 = _669 ? _668 : _652;
                _674 = mix(_653, _664, bvec4(_669));
            }
            else
            {
                _673 = _652;
                _674 = _653;
            }
            bool _678;
            if (_365)
            {
                _678 = _410 == 2;
            }
            else
            {
                _678 = true;
            }
            float _692;
            vec4 _693;
            if (_678)
            {
                vec4 _683 = textureLod(sampler2D(tex1, point_sampler), _201, 0.0);
                float _687 = abs(dot(_683.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _688 = _687 < _673;
                _692 = _688 ? _687 : _673;
                _693 = mix(_674, _683, bvec4(_688));
            }
            else
            {
                _692 = _673;
                _693 = _674;
            }
            bool _697;
            if (_388)
            {
                _697 = _410 == 2;
            }
            else
            {
                _697 = true;
            }
            float _711;
            vec4 _712;
            if (_697)
            {
                vec4 _702 = textureLod(sampler2D(tex1, point_sampler), _214, 0.0);
                float _706 = abs(dot(_702.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _707 = _706 < _692;
                _711 = _707 ? _706 : _692;
                _712 = mix(_693, _702, bvec4(_707));
            }
            else
            {
                _711 = _692;
                _712 = _693;
            }
            bool _716;
            if (_411)
            {
                _716 = _410 == 2;
            }
            else
            {
                _716 = true;
            }
            float _730;
            vec4 _731;
            if (_716)
            {
                vec4 _721 = textureLod(sampler2D(tex1, point_sampler), _226, 0.0);
                float _725 = abs(dot(_721.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _726 = _725 < _711;
                _730 = _726 ? _725 : _711;
                _731 = mix(_712, _721, bvec4(_726));
            }
            else
            {
                _730 = _711;
                _731 = _712;
            }
            bool _735;
            if (_434)
            {
                _735 = _410 == 2;
            }
            else
            {
                _735 = true;
            }
            float _751;
            vec4 _752;
            if (_735)
            {
                vec4 _742 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(2.0, 1.0) * _127), 0.0);
                float _746 = abs(dot(_742.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _747 = _746 < _730;
                _751 = _747 ? _746 : _730;
                _752 = mix(_731, _742, bvec4(_747));
            }
            else
            {
                _751 = _730;
                _752 = _731;
            }
            bool _756;
            if (_342)
            {
                _756 = _433 == 2;
            }
            else
            {
                _756 = true;
            }
            float _772;
            vec4 _773;
            if (_756)
            {
                vec4 _763 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(-2.0, 2.0) * _127), 0.0);
                float _767 = abs(dot(_763.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _768 = _767 < _751;
                _772 = _768 ? _767 : _751;
                _773 = mix(_752, _763, bvec4(_768));
            }
            else
            {
                _772 = _751;
                _773 = _752;
            }
            bool _777;
            if (_365)
            {
                _777 = _433 == 2;
            }
            else
            {
                _777 = true;
            }
            float _793;
            vec4 _794;
            if (_777)
            {
                vec4 _784 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(-1.0, 2.0) * _127), 0.0);
                float _788 = abs(dot(_784.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _789 = _788 < _772;
                _793 = _789 ? _788 : _772;
                _794 = mix(_773, _784, bvec4(_789));
            }
            else
            {
                _793 = _772;
                _794 = _773;
            }
            bool _798;
            if (_388)
            {
                _798 = _433 == 2;
            }
            else
            {
                _798 = true;
            }
            float _814;
            vec4 _815;
            if (_798)
            {
                vec4 _805 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(0.0, 2.0) * _127), 0.0);
                float _809 = abs(dot(_805.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _810 = _809 < _793;
                _814 = _810 ? _809 : _793;
                _815 = mix(_794, _805, bvec4(_810));
            }
            else
            {
                _814 = _793;
                _815 = _794;
            }
            bool _819;
            if (_411)
            {
                _819 = _433 == 2;
            }
            else
            {
                _819 = true;
            }
            float _835;
            vec4 _836;
            if (_819)
            {
                vec4 _826 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(1.0, 2.0) * _127), 0.0);
                float _830 = abs(dot(_826.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _831 = _830 < _814;
                _835 = _831 ? _830 : _814;
                _836 = mix(_815, _826, bvec4(_831));
            }
            else
            {
                _835 = _814;
                _836 = _815;
            }
            bool _840;
            if (_434)
            {
                _840 = _433 == 2;
            }
            else
            {
                _840 = true;
            }
            float _856;
            vec4 _857;
            if (_840)
            {
                vec4 _847 = textureLod(sampler2D(tex1, point_sampler), _116 + (vec2(2.0) * _127), 0.0);
                float _851 = abs(dot(_847.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)) - _250);
                bool _852 = _851 < _835;
                _856 = _852 ? _851 : _835;
                _857 = mix(_836, _847, bvec4(_852));
            }
            else
            {
                _856 = _835;
                _857 = _836;
            }
            vec3 _859 = (_237 - _236) * 0.25;
            vec3 _867 = clamp(vec3(dot(_857.xyz, vec3(0.25, 0.5, 0.25)), dot(_857.xyz, vec3(0.5, 0.0, -0.5)), dot(_857.xyz, vec3(-0.25, 0.5, -0.25))), _236 - _859, _237 + _859);
            float _868 = _867.x;
            float _869 = _867.y;
            float _871 = _867.z;
            float _878 = exp(_856 * (-20.0));
            float _884 = clamp((textureLod(sampler2D(tex2, point_sampler), _116, 0.0).y + (_878 * 0.0500000007450580596923828125)) - ((1.0 - _878) * 0.20000000298023223876953125), 0.0, 1.0);
            float _890 = clamp((0.800000011920928955078125 * _884) * (1.0 - clamp(_856 * 8.0, 0.0, 1.0)), 0.0, 1.0);
            vec3 _892 = mix(_131, vec3((_868 + _869) - _871, _868 + _871, (_868 - _869) - _871), vec3(_890));
            _910 = vec4(_892, dot(_892, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)));
            _911 = vec4(0.0, _884, length(_135 - ((((((((_145 + _157) + _170) + _183) + _196) + _209) + _222) + _234) * vec3(0.125))), _890);
        }
        imageStore(output0, ivec2(gl_GlobalInvocationID.xy), _910);
        imageStore(output1, ivec2(gl_GlobalInvocationID.xy), _911);
        break;
    } while(false);
}
